name: Build and Deploy

on:
    push:
        branches: [main, master]

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: "22"

            - run: corepack enable

            - name: Install deps
              run: pnpm install

            - name: Build plugin(s)
              run: pnpm run build

            - name: Copy README
              run: cp README.md dist/README.md

            - uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
                enable_jekyll: true
